# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: animation_data.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='animation_data.proto',
  package='AnimationSerialize',
  syntax='proto3',
  serialized_pb=_b('\n\x14\x61nimation_data.proto\x12\x12\x41nimationSerialize\"\x90\x02\n\tCurveData\x12\x0c\n\x04path\x18\x01 \x01(\t\x12:\n\x07\x63hannel\x18\x02 \x01(\x0e\x32).AnimationSerialize.CurveData.ChannelType\x12/\n\x04\x64\x61ta\x18\x03 \x03(\x0b\x32!.AnimationSerialize.CurveData.Key\x1a\x33\n\x03Key\x12\x0c\n\x04time\x18\x01 \x01(\x02\x12\r\n\x05value\x18\x02 \x01(\x02\x12\x0f\n\x07tangent\x18\x03 \x01(\x02\"S\n\x0b\x43hannelType\x12\x08\n\x04POSX\x10\x00\x12\x08\n\x04POSY\x10\x01\x12\x08\n\x04POSZ\x10\x02\x12\x08\n\x04ROTX\x10\x03\x12\x08\n\x04ROTY\x10\x04\x12\x08\n\x04ROTZ\x10\x05\x12\x08\n\x04ROTW\x10\x06\")\n\tJointNode\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0e\n\x06parent\x18\x02 \x01(\x05\"h\n\x08\x43lipData\x12-\n\x06joints\x18\x01 \x03(\x0b\x32\x1d.AnimationSerialize.JointNode\x12-\n\x06\x63urves\x18\x02 \x03(\x0b\x32\x1d.AnimationSerialize.CurveDatab\x06proto3')
)



_CURVEDATA_CHANNELTYPE = _descriptor.EnumDescriptor(
  name='ChannelType',
  full_name='AnimationSerialize.CurveData.ChannelType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='POSX', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='POSY', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='POSZ', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ROTX', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ROTY', index=4, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ROTZ', index=5, number=5,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ROTW', index=6, number=6,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=234,
  serialized_end=317,
)
_sym_db.RegisterEnumDescriptor(_CURVEDATA_CHANNELTYPE)


_CURVEDATA_KEY = _descriptor.Descriptor(
  name='Key',
  full_name='AnimationSerialize.CurveData.Key',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='time', full_name='AnimationSerialize.CurveData.Key.time', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='AnimationSerialize.CurveData.Key.value', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tangent', full_name='AnimationSerialize.CurveData.Key.tangent', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=181,
  serialized_end=232,
)

_CURVEDATA = _descriptor.Descriptor(
  name='CurveData',
  full_name='AnimationSerialize.CurveData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='path', full_name='AnimationSerialize.CurveData.path', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='channel', full_name='AnimationSerialize.CurveData.channel', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='AnimationSerialize.CurveData.data', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_CURVEDATA_KEY, ],
  enum_types=[
    _CURVEDATA_CHANNELTYPE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=45,
  serialized_end=317,
)


_JOINTNODE = _descriptor.Descriptor(
  name='JointNode',
  full_name='AnimationSerialize.JointNode',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='AnimationSerialize.JointNode.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='parent', full_name='AnimationSerialize.JointNode.parent', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=319,
  serialized_end=360,
)


_CLIPDATA = _descriptor.Descriptor(
  name='ClipData',
  full_name='AnimationSerialize.ClipData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='joints', full_name='AnimationSerialize.ClipData.joints', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='curves', full_name='AnimationSerialize.ClipData.curves', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=362,
  serialized_end=466,
)

_CURVEDATA_KEY.containing_type = _CURVEDATA
_CURVEDATA.fields_by_name['channel'].enum_type = _CURVEDATA_CHANNELTYPE
_CURVEDATA.fields_by_name['data'].message_type = _CURVEDATA_KEY
_CURVEDATA_CHANNELTYPE.containing_type = _CURVEDATA
_CLIPDATA.fields_by_name['joints'].message_type = _JOINTNODE
_CLIPDATA.fields_by_name['curves'].message_type = _CURVEDATA
DESCRIPTOR.message_types_by_name['CurveData'] = _CURVEDATA
DESCRIPTOR.message_types_by_name['JointNode'] = _JOINTNODE
DESCRIPTOR.message_types_by_name['ClipData'] = _CLIPDATA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CurveData = _reflection.GeneratedProtocolMessageType('CurveData', (_message.Message,), dict(

  Key = _reflection.GeneratedProtocolMessageType('Key', (_message.Message,), dict(
    DESCRIPTOR = _CURVEDATA_KEY,
    __module__ = 'animation_data_pb2'
    # @@protoc_insertion_point(class_scope:AnimationSerialize.CurveData.Key)
    ))
  ,
  DESCRIPTOR = _CURVEDATA,
  __module__ = 'animation_data_pb2'
  # @@protoc_insertion_point(class_scope:AnimationSerialize.CurveData)
  ))
_sym_db.RegisterMessage(CurveData)
_sym_db.RegisterMessage(CurveData.Key)

JointNode = _reflection.GeneratedProtocolMessageType('JointNode', (_message.Message,), dict(
  DESCRIPTOR = _JOINTNODE,
  __module__ = 'animation_data_pb2'
  # @@protoc_insertion_point(class_scope:AnimationSerialize.JointNode)
  ))
_sym_db.RegisterMessage(JointNode)

ClipData = _reflection.GeneratedProtocolMessageType('ClipData', (_message.Message,), dict(
  DESCRIPTOR = _CLIPDATA,
  __module__ = 'animation_data_pb2'
  # @@protoc_insertion_point(class_scope:AnimationSerialize.ClipData)
  ))
_sym_db.RegisterMessage(ClipData)


# @@protoc_insertion_point(module_scope)
