// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: animation_data.proto

#pragma warning disable 1591, 0612, 3021

namespace AnimationSerialize
{

    [global::ProtoBuf.ProtoContract()]
    public partial class CurveData
    {
        public CurveData()
        {
            Path = "";
            Datas = new global::System.Collections.Generic.List<Key>();
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1, Name = @"path")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Path { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"channel")]
        public ChannelType Channel { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"data")]
        public global::System.Collections.Generic.List<Key> Datas { get; private set; }

        [global::ProtoBuf.ProtoContract()]
        public partial class Key
        {
            public Key()
            {
                OnConstructor();
            }

            partial void OnConstructor();

            [global::ProtoBuf.ProtoMember(1, Name = @"time")]
            public float Time { get; set; }

            [global::ProtoBuf.ProtoMember(2, Name = @"value")]
            public float Value { get; set; }

            [global::ProtoBuf.ProtoMember(3, Name = @"tangent")]
            public float Tangent { get; set; }

        }

        [global::ProtoBuf.ProtoContract()]
        public enum ChannelType
        {
            [global::ProtoBuf.ProtoEnum(Name = @"POSX")]
            Posx = 0,
            [global::ProtoBuf.ProtoEnum(Name = @"POSY")]
            Posy = 1,
            [global::ProtoBuf.ProtoEnum(Name = @"POSZ")]
            Posz = 2,
            [global::ProtoBuf.ProtoEnum(Name = @"ROTX")]
            Rotx = 3,
            [global::ProtoBuf.ProtoEnum(Name = @"ROTY")]
            Roty = 4,
            [global::ProtoBuf.ProtoEnum(Name = @"ROTZ")]
            Rotz = 5,
            [global::ProtoBuf.ProtoEnum(Name = @"ROTW")]
            Rotw = 5,
        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ClipData
    {
        public ClipData()
        {
            Curves = new global::System.Collections.Generic.List<CurveData>();
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1, Name = @"curves")]
        public global::System.Collections.Generic.List<CurveData> Curves { get; private set; }

    }

}

#pragma warning restore 1591, 0612, 3021
